### ISSUE TITLE
Pure CSS Icons ?

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#11]
Do you think it's a good idea to add pur css icons ?

http://nicolasgallagher.com/pure-css-gui-icons/demo/
http://rathersplendid.net/cssicons/

We do not want something like http://graphicpeel.com/cssiosicons

But do we want something like http://nicolasgallagher.com/pure-css-social-media-icons/demo/ ?

**Comment by davidkaneda** [comment]
We can ask NIcolas if he'd like to contribute — otherwise, I think we should just include a mixin for styling webfont-driven and unicode icons (I may just have one ready...) that asks for the character, and uses techniques like this: http://css-tricks.com/examples/IconFont/, including setting content on before/after for extra effects.

**Comment by MoOx** [comment]
Insane. Use custom icon fonts (fontcustom, fontforge, grunt-webfont...) instead.
