### ISSUE TITLE
Add webfont icons recipes

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#19]
Using this http://www.justbenicestudio.com/studio/websymbols/  ?
To get something like @adamstac does with pictos free here https://github.com/adamstac/pictos-free but with webfonts !
Will be awesome, right ?

List of fonts
- http://www.justbenicestudio.com/studio/websymbols/
- http://somerandomdude.com/work/iconic/
- http://www.heydonworks.com/a-free-icon-web-font

**Comment by adamstac** [comment]
I created a Sass and Compass project for the websymbols icons, but didn't publish it yet.

**Comment by MoOx** [comment]
Maybe you could share it here ? ;)

**Comment by adamstac** [comment]
As much as I'd love to contribute (and support the Sass community) I just don't get the swiss-army knife approach here. We likely have differing opinions, but this project just seems so heavy and bulky vs choosing a project a la carte and using it. For example, if someone wants to use Zocial, Grid Coordinates, Pictos Free or any other Sass project out there, they just use it.

Trust me when I say that I don't think what you are doing here is bad, cause it's certainly helpful to some. I just don't get the whole everything in one project/library approach.

All that to say that I didn't publish the Web Symbols project yet because I never ended up using it, and we both know that as soon as you release something you are bound to support it as well. I just didn't want to take that extra project load on right now.

**Comment by MoOx** [comment]
I understand your point of view.
With compass-recipes, I don't want to create a big project with lots of sub project. You are completely right to say your project like Zocial, Grid Coord... etc must have dedicated project.
I just want a library, with tiny recipes which do not have their place into dedicated repo. Recipes you can use in all of your projects. Recipes that huge projects can use, like Compass is used :)

For this issue (webfont icons) maybe this is a huge deal. I'll see. It's maybe a bad idea.

**Comment by davidkaneda** [comment]
@Moox Happy to contribute one I have, but I need to get that Color PR in there :)

**Comment by MoOx** [comment]
Maybe we can add a helper based on the data-\* technique
http://24ways.org/2011/displaying-icons-with-fonts-and-data-attributes

**Comment by davidkaneda** [comment]
Sounds good. Just FYI, I'm going to start making obvious patches/fixes/enhancements directly to master, but anything which is subjective, or deprecates mixins/variables I'll keep sending via pull request.

Thanks,
Dave

**Comment by MoOx** [comment]
Have fun with it :)

**Comment by davidkaneda** [comment]
No doubt :) http://cl.ly/Cajj

**Comment by davidkaneda** [comment]
Webfont-icon mixin and the fonts you listed which are OFL are in.
